version: '3.9'
services:
  easy_find_db_test:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      TZ: ${TZ}
    ports:
      - ${POSTGRES_PORT_TEST}:5432
    volumes:
      - pgdata:/data/postgres

  easy_find_cache_test:
    image: redis
    command: ["redis-server", "--aclfile /data/users.acl"]
    volumes:
      - ./users.acl:/data/users.acl
    ports:
      - "${REDIS_CACHE_PORT_TEST}:6379"
    

volumes:
  pgdata:
    driver: local